ignorePatterns:
  - '/scripts'
  - '/public'
  - '/assets/js'
env:
  browser: true
  es6: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:prettier/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 11
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  linebreak-style:
    - error
    - unix
  curly:
    - error
    - all
  eqeqeq:
    - error
    - always
