extends:
  - stylelint-config-sass-guidelines

rules:
  selector-no-qualifying-type: null
  selector-max-id: null
  color-named: null
  declaration-property-value-blacklist: null
  max-nesting-depth: null
  selector-max-compound-selectors: null
  scss/dollar-variable-pattern: null

ignoreFiles:
  - "node_modules/**/*"
  - "public/**/*"
  - "assets/css/vendor/**/*"
