baseURL = "https://2cat.cc"
title = "双猫CC"

languageCode = "zh"
defaultContentLanguage = "zh"
hasCJKLanguage = true
enableEmoji = true
enableRobotsTXT = true

disqusShortname = "2cat"

theme = ["hugo-notepadium"]

[markup.highlight]
codeFences = true
noClasses = false

[author]
name = "rydesun"
email = "rydesun@gmail.com"

[params]
dateFormat = "2006年01月02日"
fullRss = true
license = '<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="知识共享许可协议" src="/images/cc-80x15.png" /></a><p>© 2020 rydesun</p>'

[params.comments]
enable=true

[params.nav]
showCategories = true
showTags = true

[[params.nav.custom]]
title = "CatchCat"
url = "/about/"

[params.assets]
css = ["css/tweak.sass"]
js = ["js/ie-warn.js"]

[params.syntax]
theme = "friendly"
darkTheme = "dracula"
