baseURL = "https://2cat.cc"
title = "2cat.cc"

languageCode = "zh-cn"
hasCJKLanguage = true
enableEmoji = true
enableRobotsTXT = true

disqusShortname = "2cat"

theme = ["hugo-notepadium"]

[markup.highlight]
codeFences = true
noClasses = false

[params]
dateFormat = "2006年01月02日"
slogan = "rydesun的博客"
fullRss = true
license = '<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="知识共享许可协议" style="border-width:0" src="/images/cc-80x15.png" /></a><br><span>© 2020 rydesun<span>'

[params.comments]
enable=true

[params.nav]
showCategories = true
showTags = true

[[params.nav.custom]]
title = "CatchCat"
url = "/about/"

[params.assets]
css = ["css/tweak.css"]

[params.syntax]
theme = "friendly"
darkTheme = "solarized-dark256"
