baseURL = "https://catcat.cc"
title = "双猫CC"

languageCode = "zh"
defaultContentLanguage = "zh"
hasCJKLanguage = true
enableEmoji = true
enableRobotsTXT = true

[markup]
  defaultMarkdownHandler = "blackfriday"
  [markup.blackFriday]
    extensions = ["joinLines"]
    hrefTargetBlank = true
    nofollowLinks = true
    noreferrerLinks = true

[markup.highlight]
codeFences = true
noClasses = false

[author]
name = "rydesun"
email = "rydesun@gmail.com"

[params]
description = "rydesun的纸箱猫窝，快看看里面收集了哪些宝贝！"
staticBaseURL = "https://static.catcat.cc"
dateFormat = "2006年01月02日"
fullRss = true

[params.comments]
enable=true

[params.nav]
showCategories = true
showTags = true

[[params.nav.custom]]
title = "CatchCat"
url = "/about/"

[outputs]
home = ["HTML"]
page = ["HTML"]
section = ["RSS"]
taxonomy = ["HTML"]
term = ["HTML"]
